#### 0.1.1 - 2025 - 06 - 01
#### Dr. Marco Antonio Aceves
#### rev en Jupyter Notebook
#### Código como ejemplo como parte del libro:
#### de 0 a 100 en Inteligencia Artificial
#### 4_Q-Learning

In [ ]:
!pip install --upgrade gym gymnasium

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 721.7/721.7 kB 9.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for gym: filename=gym-0.26.2-py3-none-any.whl size=827728 sha256=61161561f40e2e6a21f8ead0f17d4383b925d3467be6603fe175389c22e4a013
  Stored in directory: /root/.cache/pip/wheels/1c/77/9e/9af5470201a0b0543937933ee99ba884cd237d2faefe8f4d37
Successfully built gym
  Attempting uninstall: gym
    Found existing installation: gym 0.25.2
    Uninstalling gym-0.25.2:
      Successfully uninstalled gym-0.25.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dopamine-rl 4.1.2 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.


In [ ]:
#Importar librerías
import numpy as np
import gym

In [ ]:
# Crear el entorno FrozenLake (4x4)

# is_slippery=False para que no sea aleatorio
env = gym.make("FrozenLake-v1", is_slippery=False)

# Parámetros del entorno
# 16 estados
n_states = env.observation_space.n
# 4 acciones (izq, abajo, der, arriba)
n_actions = env.action_space.n


# Crear e inicializar la tabla Q
Q = np.zeros((n_states, n_actions))

In [ ]:
# Parámetros de Q-learning
# El significado de cada parámetro se muestra en el libro
alpha = 0.1      # Tasa de aprendizaje
gamma = 0.99     # Factor de descuento
epsilon = 0.1    # Exploración
n_episodes = 1000

In [ ]:
# Entrenamiento
for episode in range(n_episodes):
    # En las versiones recientes de gym/gymnasium, env.reset() devuelve una tupla (observation, info)
    state, info = env.reset()
    done = False

    while not done:
        # Elegir acción (exploración vs explotación)
        if np.random.rand() < epsilon:
            action = env.action_space.sample()  # Explora
        else:
            action = np.argmax(Q[state])        # Explota
        # En las versiones recientes de gym/gymnasium, step() devuelve una tupla (observation, reward, terminated, truncated, info)
        next_state, reward, terminated, truncated, info = env.step(action)

        # 'done' en la API antigua es 'terminated or truncated' en la nueva API
        done = terminated or truncated

        # Actualización Q-learning
        best_next_action = np.max(Q[next_state])
        Q[state, action] += alpha * (reward + gamma * best_next_action - Q[state, action])

        # Pasar al siguiente estado
        state = next_state

# Mostrar la tabla Q aprendida
print("Tabla Q (valores aprendidos):")
print(np.round(Q, 2))


Tabla Q (valores aprendidos):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
